### ISSUE TITLE
Add iOS/Android nightly builds + release build publishing

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#10551]
After https://github.com/mapbox/mapbox-gl-native/pull/10257 landed and we disabled all Bitrise builds for master, we can now start working on automatically building nightly releases for iOS/Android, as well as automating release publishing when pushing tags.

/cc @tobrun @friedbunny

**Comment by tobrun** [comment]
An [example](https://github.com/mapbox/mapbox-android-demo/blob/6741fb41fed0e1c1fd12b10484ed2d9a3b4cb514/circle.yml) of reacting tag creation can be found in the demo app repo (there we release a new version of the application to Google Play when a new tag is created).

**Comment by friedbunny** [comment]
Per [docs](https://circleci.com/docs/2.0/workflows/#git-tag-job-execution), if you want to make a job tag-only, you must also explicitly ignore all branches:

```
- ios-release:
    filters:
      tags:
        only: /ios-.*/
      branches:
        ignore: /.*/
```
