### ISSUE TITLE
Gradle dependency caching on CircleCI

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#9352]
To improve build times we can cache our gradle dependencies on top of the node_modules + ccache. 

```
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
```

https://circleci.com/docs/2.0/language-android/
