### ISSUE TITLE
[ANDROID] Help debugging native crash, SIGSEGV

### ISSUE THREAD

**Issue by sddamico** [mapbox/mapbox-gl-native#9510]
**Platform:** Android
**Mapbox SDK version:** 5.0.2

### Steps to trigger behavior

I've been consistently unable to trigger this error locally, though it is reported often to my store listing on the Play Store as crashes. It seems to have picked up in rate when we moved from 4.x to 5.0.2 on June 7th. There's no discernable patterns in the types of devices that the issue is occurring on. From taking a sampling of the recent reported issues, this is occurring on most modern devices (samsung galaxy s7, s8, etc).

This is the title of the issue:

![](https://cl.ly/1f2p0W1u2K3R/Image%202017-07-13%20at%203.51.47%20PM.png)

And the backtrace that the play store gives:

```
backtrace:
  native: pc 00000000004280f0  /system/lib64/libart.so (_ZN3art35InvokeVirtualOrInterfaceWithVarArgsERKNS_33ScopedObjectAccessAlreadyRunnableEP8_jobjectP10_jmethodIDSt9__va_list+88)
  native: pc 0000000000331230  /system/lib64/libart.so (_ZN3art3JNI15CallVoidMethodVEP7_JNIEnvP8_jobjectP10_jmethodIDSt9__va_list+624)
  native: pc 0000000000036754  /data/app/com.seatgeek.android-1/lib/arm64/libmapbox-gl.so
  native: pc 0000000000036698  /data/app/com.seatgeek.android-1/lib/arm64/libmapbox-gl.so
  native: pc 000000000007ab9c  /data/app/com.seatgeek.android-1/lib/arm64/libmapbox-gl.so
  native: pc 000000000002f718  /data/app/com.seatgeek.android-1/lib/arm64/libmapbox-gl.so
  native: pc 000000000002f32c  /data/app/com.seatgeek.android-1/lib/arm64/libmapbox-gl.so
  native: pc 0000000000018254  /system/lib64/libutils.so (_ZN7android6Looper9pollInnerEi+852)
  native: pc 0000000000017e50  /system/lib64/libutils.so (_ZN7android6Looper8pollOnceEiPiS1_PPv+60)
  native: pc 00000000000f790c  /system/lib64/libandroid_runtime.so (_ZN7android18NativeMessageQueue8pollOnceEP7_JNIEnvP8_jobjecti+48)
  native: pc 0000000002972360  /system/framework/arm64/boot-framework.oat (android.os.MessageQueue.nativePollOnce+140)
  native: pc 0000000002973f70  /system/framework/arm64/boot-framework.oat (android.os.MessageQueue.next+236)
  native: pc 000000000296da98  /system/framework/arm64/boot-framework.oat (android.os.Looper.loop+340)
  native: pc 000000000206f204  /system/framework/arm64/boot-framework.oat (android.app.ActivityThread.main+768)
  native: pc 00000000000d1de8  /system/lib64/libart.so (art_quick_invoke_static_stub+600)
  native: pc 00000000000de830  /system/lib64/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+252)
  native: pc 0000000000426c70  /system/lib64/libart.so (_ZN3artL18InvokeWithArgArrayERKNS_33ScopedObjectAccessAlreadyRunnableEPNS_9ArtMethodEPNS_8ArgArrayEPNS_6JValueEPKc+108)
  native: pc 00000000004287e0  /system/lib64/libart.so (_ZN3art12InvokeMethodERKNS_33ScopedObjectAccessAlreadyRunnableEP8_jobjectS4_S4_m+1188)
  native: pc 00000000003a15ec  /system/lib64/libart.so (_ZN3artL13Method_invokeEP7_JNIEnvP8_jobjectS3_S3_+56)
  native: pc 0000000000673248  /system/framework/arm64/boot.oat (java.lang.reflect.Method.invoke+180)
  native: pc 0000000003127450  /system/framework/arm64/boot-framework.oat (com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run+124)
  native: pc 0000000003128f30  /system/framework/arm64/boot-framework.oat (com.android.internal.os.ZygoteInit.main+1484)
  native: pc 00000000000d1de8  /system/lib64/libart.so (art_quick_invoke_static_stub+600)
  native: pc 00000000000de830  /system/lib64/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+252)
  native: pc 0000000000426c70  /system/lib64/libart.so (_ZN3artL18InvokeWithArgArrayERKNS_33ScopedObjectAccessAlreadyRunnableEPNS_9ArtMethodEPNS_8ArgArrayEPNS_6JValueEPKc+108)
  native: pc 00000000004268c8  /system/lib64/libart.so (_ZN3art17InvokeWithVarArgsERKNS_33ScopedObjectAccessAlreadyRunnableEP8_jobjectP10_jmethodIDSt9__va_list+380)
  native: pc 0000000000343418  /system/lib64/libart.so (_ZN3art3JNI21CallStaticVoidMethodVEP7_JNIEnvP7_jclassP10_jmethodIDSt9__va_list+604)
  native: pc 00000000000a52f8  /system/lib64/libandroid_runtime.so
  native: pc 00000000000a7a88  /system/lib64/libandroid_runtime.so (_ZN7android14AndroidRuntime5startEPKcRKNS_6VectorINS_7String8EEEb+712)
  native: pc 0000000000004708  /system/bin/app_process64
  native: pc 000000000001a958  /system/lib64/libc.so (__libc_init+88)
  native: pc 0000000000003ffc  /system/bin/app_process64
```

I would love to know if this is something I'm doing wrong when using the SDK or what... I'm not sure how to go forward from here in terms of collecting a more detailed trace or debugging how I might reproduce this crash locally... I have very little experience working with native code on Android.
